package com.board.error;

public enum MemberError {
	NO_ERROR,
//	DB_FAIL,
	INVALID_BIRTHDAY,
	INVALID_EMAIL,
	INVALID_PASSWORD,
	INVALID_ID,
	DUPLICATE_ID,
	INVALID_NICKNAME,
	DUPLICATE_NICKNAME,
	WRONG_PASSWORD
}
